### ISSUE TITLE
I don't understand ?

### ISSUE THREAD

**Issue by sertacyigitcanhalici** [Kibo/AstroChart#34]
Is there a way to generate svg and send it or i can only  use it inside html when i try to use it outside of html says document not found (i want to run it on the server convert the data to png and send it to the frontend(flutter)) if there is  a way could you please help me thanks.

**Comment by afucher** [comment]
Hi @sertacyigitcanhalici ,

We are moving this repo to https://github.com/AstroDraw/AstroChart.
All the issues will be handled there.

As I said by email, this library just works inside a browser, at least for now.

Since this is not an issue related to the library, and more related to how to render an html in the server side, I'll ask you to post it on [StackOverflow](https://stackoverflow.com/). Probably there will be people that can help you with that question.

If you have any issue related to the project, feel free to open a new issue on the new repo.

**Comment by sertacyigitcanhalici** [comment]
Sure thanks for letting me know
